---
title: "by_year"
author: "yiren"
date: "06/11/2021"
output: html_document
---


```{r, echo=FALSE, cache=FALSE, include = FALSE, message = FALSE}
pacman::p_load(tidyverse, pacman, ggmap, janitor, sf, mapview, leaflet, rgdal, RColorBrewer, ggplot2, data.table, readr, qqplotr, GGally, lubridate, raster, spData, spDataLarge, tmap, osmdata, gifski, jsonlite)

#Register API key to google
register_google(key="AIzaSyBT6yzDKV_DGcFGK9E-cXu0zNUD4WTJOZA")

#Get location of chicago
chicago <- geocode("Chicago, IL")

#Make leaflet map with chicago center
chicago_leaflet <- leaflet() %>% 
  setView(lng=chicago$lon, lat=chicago$lat, zoom=10) %>%
  addProviderTiles(providers$CartoDB.Positron) 
```

Loading some data

```{r pressure, echo=FALSE, message = FALSE}
count_per_year<- jsonlite::fromJSON("./data/count_per_year.json", flatten=TRUE)
trip_total_per_year<-jsonlite::fromJSON("./data/trip_total_per_year.json", flatten=TRUE)
trip_total_per_year_per_zone<-jsonlite::fromJSON("./data/trip_total_per_year_per_zone.json", flatten=TRUE)

count_vs_triptotal <- 
```

Do we need to standardise 2021? Yes, while doing analysis.

Count vs Total Revenue by year
```{r}
p <- ggplot(cars, aes(speed, dist)) +
  geom_point()
# Add regression line
p + geom_smooth(method = lm)

```

